import { GetServerSideProps } from 'next';
import { FunctionComponent } from 'react';
import Head from 'next/head';
import { useQuery } from 'react-query';

const Home: FunctionComponent = () => {
  const { isLoading, isError, isSuccess, data } = useQuery(['drivers'], () =>
    fetch('http://localhost:3000/api/drivers').then(res => res.json())
  );
  console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{/* <h1>Fantasy F1</h1> */}</main>
    </div>
  );
};

export default Home;
